/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ConceptConceptIdRouteImport } from './routes/concept.$conceptId'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptConceptIdRoute = ConceptConceptIdRouteImport.update({
  id: '/concept/$conceptId',
  path: '/concept/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => GoalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/goals': typeof GoalsRouteWithChildren
  '/journey': typeof JourneyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/concept/$conceptId': typeof ConceptConceptIdRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/goals'
    | '/journey'
    | '/profile'
    | '/resources'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/concept/$conceptId'
    | '/goals/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/goals'
    | '/journey'
    | '/profile'
    | '/resources'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/concept/$conceptId'
    | '/goals/$goalId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/goals'
    | '/journey'
    | '/profile'
    | '/resources'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/concept/$conceptId'
    | '/goals/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GoalsRoute: typeof GoalsRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ConceptConceptIdRoute: typeof ConceptConceptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept/$conceptId': {
      id: '/concept/$conceptId'
      path: '/concept/$conceptId'
      fullPath: '/concept/$conceptId'
      preLoaderRoute: typeof ConceptConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof GoalsRoute
    }
  }
}

interface GoalsRouteChildren {
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsGoalIdRoute: GoalsGoalIdRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GoalsRoute: GoalsRouteWithChildren,
  JourneyRoute: JourneyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ConceptConceptIdRoute: ConceptConceptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
